### ISSUE TITLE
Allow local mboxs/commits

### ISSUE THREAD

**Issue by lsandoval** [lsandoval/patchtest#1]
Instead of fetching mboxes from a patchwork instances, it is useful to take a certain mbox from a local file and apply it to the repo. In other words, instead of using 'git pw as' programatically, one would use git am directly.

This feature will also help on the near future to unit testing the system, and now relying on a outside patchwork instance.

To be assigned to Alex Franco as soon as he forks the repo.

**Comment by lsandoval** [comment]
The system should allow local commits as inputs. 

Possible scenario:

```
pathctest -1 # for git commits
patchtest ./1.mbox # for mbox
patchtest -s 919 -r 1 # for a patchwork series/revisions
```

**Comment by aphran** [comment]
It would also be nice some options could work with several items, rather than just one:

--mbox could take more than one file, or directories containing mbox files
--commit could take a commit range
--branch could take a list of branches

Maybe these could be further enhancements, we can start with the simpler case of taking one item per parameter

**Comment by aphran** [comment]
Note: talk about whether local and patchwork related parameters should be mutually exclusive or both applicable. For now, mutual exclusiveness should suffice.

**Comment by lsandoval** [comment]
Regarding the comment https://github.com/lsandoval/patchtest/issues/1#issuecomment-172057504, I completely agree. 

Currently, --commit and --branch parameters have two meanings depending if -s/-r or -m are present or not

1. if present: tell the system where to create a temporally branch and apply the mbox

2. if not present: just create the branch 

After 1 or 2, the system starts testing.

So, in case of commit ranges or branches, we should have another set of parameters, and the point here would be naming.

**Comment by lsandoval** [comment]
Regarding https://github.com/lsandoval/patchtest/issues/1#issuecomment-172058609, I agree. we should mutual exclude these, so we can either use patchwork mboxes or local mboxes.

**Comment by lsandoval** [comment]
Command line examples using stdin as input and command line arguments


* STDIN input

```
    $ git pw poll-events | patchtest
    $ ls /path/to/mboxes/* | patchtest
```

* Command line input

```
   patchtest -s X -r Y
   patchtest -m /path/to/mboxes/*
   patchtest -c <commit>
   patchtest -b <branch>
```

**Comment by lsandoval** [comment]
A whole refactor has been done to patchtest and now it allow either series/mbox, from command line or stdin.
