### ISSUE TITLE
A branch for tests

### ISSUE THREAD

**Issue by aphran** [lsandoval/patchtest#6]
I think it would be a good idea to create a branch where we can contribute tests

**Comment by lsandoval** [comment]
@aphran I have the idea to keep it in a completely separate repository, so detaching the framework from the test cases. Also, we can have 'base' tests to check things like trailing spaces found in the mbox. Individual projects can make use of git submodules, and these submodules correspond to separate test repos.

**Comment by aphran** [comment]
@lsandoval indeed, I have created the repo https://github.com/aphran/pt-suites for this
